Set version in file to allow action to modify it (#36)
* Set version in file to allow action to modify it

Github does not allow an action to modify an action when ran as a github app.

The issue is resolved by adding a version file, this file can be edited by the update action and read by the deploy action.

**Error**:

```
Run yq e '.env.BASE_IMAGE_VERSION = "v0.0.9"' -i .github/workflows/kildomaten.yaml
[main d28e09c] Use dapla-source-data-processor v0.0.9
 1 file changed, 13 insertions(+), 60 deletions(-)
remote: error: GH013: Repository rule violations found for refs/heads/main.
remote: Review all repository rules at http://github.com/statisticsnorway/dapla-source-data-processor-build-scripts/rules?ref=refs%2Fheads%2Fmain
remote:
remote: - refusing to allow a GitHub App to create or update workflow `.github/workflows/kildomaten.yaml` without `workflows` permission
remote:
To https://github.com/statisticsnorway/dapla-source-data-processor-build-scripts
 ! [remote rejected] main -> main (push declined due to repository rule violations)
error: failed to push some refs to 'https://github.com/statisticsnorway/dapla-source-data-processor-build-scripts'
Error: Process completed with exit code 1.
```

* Remove global version env var, since this is replaced by `needs.fetch_sources.outputs.base_image_version`